name: Publish PR

on:
  workflow_run:
    workflows: [ 'Upload PR' ]
    types: [ completed ]
  issue_comment:
    types: [ edited ]
  pull_request_target:
    types: [ opened ]

permissions:
  packages: write
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish-pr:
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-pr.yml@master
    secrets: inherit